# Generated by Django 3.0 on 2020-09-11 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Calificaciones', '0001_initial'),
        ('Trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificado', to='Trabajadores.Trabajadores'),
        ),
    ]
