# Generated by Django 3.0 on 2020-09-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calificaciones', '0002_calificaciones_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='calificacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
