# Generated by Django 3.0 on 2020-09-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stalkers', '0004_remove_stalkers_calificacion'),
        ('Calificaciones', '0003_auto_20200919_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='stalker',
            field=models.ManyToManyField(blank=True, related_name='califica', to='Stalkers.Stalkers'),
        ),
    ]
