# Generated by Django 3.0 on 2020-09-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calificaciones', '0004_calificaciones_stalker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificaciones',
            name='comentario',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
