# Generated by Django 3.0 on 2020-09-19 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stalkers', '0003_stalkers_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stalkers',
            name='calificacion',
        ),
    ]
