# Generated by Django 3.0 on 2020-09-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pub', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
