# Generated by Django 3.0 on 2020-09-11 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stalkers', '0001_initial'),
        ('Comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='stalker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comento', to='Stalkers.Stalkers'),
        ),
    ]
