# Generated by Django 3.0 on 2020-09-11 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comentarios', '0002_comentarios_stalker'),
        ('Trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentado', to='Trabajadores.Trabajadores'),
        ),
    ]
