# Generated by Django 3.0 on 2020-09-11 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('especialidad', models.CharField(max_length=20)),
                ('certificado', models.ImageField(blank=True, null=True, upload_to='Trabajadores')),
                ('rubro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filtro_rubro', to='Trabajadores.Rubros')),
            ],
        ),
    ]
