# Generated by Django 3.0 on 2020-09-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trabajadores', '0002_trabajadores_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='especialidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trabajadores',
            name='promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
