# Generated by Django 3.0 on 2020-09-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zonas', '0001_initial'),
        ('Trabajadores', '0003_auto_20200914_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadores',
            name='zonas',
            field=models.ManyToManyField(related_name='Opera', to='Zonas.Zonas'),
        ),
    ]
