# Generated by Django 3.0 on 2020-09-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zonas', '0001_initial'),
        ('Trabajadores', '0005_auto_20200916_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='zonas',
            field=models.ManyToManyField(blank=True, related_name='Opera', to='Zonas.Zonas'),
        ),
    ]
