# Generated by Django 3.0 on 2020-09-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trabajadores', '0006_auto_20200916_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='promedio',
            field=models.FloatField(),
        ),
    ]
