# Generated by Django 3.0 on 2020-09-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trabajadores', '0007_auto_20200919_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='promedio',
            field=models.FloatField(default=0),
        ),
    ]
